export const API_ENVIRONMENT = Symbol('API_ENVIRONMENT');
export const DATABASE_CLIENT = Symbol('DATABASE_CLIENT');
export const AUTH_SERVICE = Symbol('AUTH_SERVICE');
export const CATALOG_SERVICE = Symbol('CATALOG_SERVICE');
export const FEISHU_IDENTITY_PROVIDER = Symbol('FEISHU_IDENTITY_PROVIDER');
export const INVENTORY_QUERY_SERVICE = Symbol('INVENTORY_QUERY_SERVICE');
export const PRODUCT_IMAGE_CONTENT_PROVIDER = Symbol('PRODUCT_IMAGE_CONTENT_PROVIDER');
export const WAREHOUSE_DIRECTORY_SERVICE = Symbol('WAREHOUSE_DIRECTORY_SERVICE');
